version: '3.1'

services:
#base de datos
  sqlserver_db:
  # nombre del contenedor
    container_name: sql2019docker
    image: mcr.microsoft.com/mssql/server:2019-latest
    restart: always
    ports:
      - 1433:1433
    # en windows los volumenes se separan en los primeros 3
    # se incluye el 4to volumen de forma opcional
    volumes:
      - c:\docker\volumes\sqlserver2019\data:/var/opt/mssql/data
      - c:\docker\volumes\sqlserver2019\log:/var/opt/mssql/log
      - c:\docker\volumes\sqlserver2019\secrets:/var/opt/mssql/secrets
      - c:\docker\volumes\sqlserver2019\tmp:/var/tmp
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: sa1105.DP1105.@awkh.2

  lombaapi:
    build:
      context: ./Lomba.API
    container_name: lombaapidocker
    environment:
      ASPNETCORE_ENVIRONMENT: Staging
    depends_on:
      - sqlserver_db
    ports:
      - 8087:80
