version: '3.1'

services:
#base de datos
  sqlserver_db:
  # nombre del contenedor
    container_name: sql2019docker
    image: mcr.microsoft.com/mssql/server:2019-latest
    restart: always
    networks:
      - netbackend
    ports:
      - 14331:1433
    # en windows los volumenes se separan en los primeros 3
    # se incluye el 4to volumen de forma opcional
    volumes:
      - c:\docker\volumes\sqlserver2019\data:/var/opt/mssql/data
      - c:\docker\volumes\sqlserver2019\log:/var/opt/mssql/log
      - c:\docker\volumes\sqlserver2019\secrets:/var/opt/mssql/secrets
      - c:\docker\volumes\sqlserver2019\tmp:/var/tmp
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: sa1105.DP1105.@awkh.2

  lombaapi:
    build:
      context: ./Lomba.API
    networks:
      - netbackend
    container_name: lombaapidocker
    environment:
      ASPNETCORE_ENVIRONMENT: Staging
    depends_on:
      - sqlserver_db
    ports:
      - 8081:80

networks:
  netbackend:
    driver: bridge
    driver_opts:
            com.docker.network.enable_ipv6: "true"
    ipam:
        driver: default
        config:
        -
          subnet: 172.16.232.0/24
          gateway: 172.16.232.1
        -
          subnet: "2001:3974:3979::/64"
          gateway: "2001:3974:3979::1"